import { CardCategory } from "@/components/shared/CategorizedSection";
import { asset } from "@/lib/assets";

const logo = (name: string) => asset(`/images/azulzinha-smart/logo/${name}.png`);

const appsData: CardCategory[] = [
    {
        label: "Todos os apps",
        items: [
            { title: "A00s", logo: logo("logo-a00s"), description: "O App A00s funciona como PDV móvel, mas também como check out remoto, tanto para comércio, como para bares e restaurantes. Atende pequenos comércios, que pode usar apenas o terminal, como o médio e grande que pode trabalhar interligado com outras soluções." },
            { title: "A2D Ticket", logo: logo("logo-a2d-ticket"), description: "O A2D Ticket é um aplicativo de venda e gestão de ingressos digitais, desenvolvido pela A2D Soluções LTDA. A solução oferece uma plataforma completa para eventos, permitindo a criação, venda, acompanhamento e validação de ingressos de forma digital, com controle em tempo real das vendas e dos repasses financeiros." },
            { title: "Alpino", logo: logo("logo-alpino"), description: "O Alpino Smart é uma solução completa oferecida pela Alpino Comércio de Hardware e Serviços LTDA para auxiliar pequenas e médias empresas na emissão de NFC-e (Nota Fiscal de Consumidor Eletrônica). Com total conformidade com as normativas vigentes, o Alpino Smart já realiza a vinculação obrigatória do comprovante de pagamento à NFC-e." },
            { title: "Anota Ai Smart PDV",  logo: logo("logo-new-choice"), description: "A gestão de frente de loja ficará mais simples e rápida. Utilizando o dinamismo e praticidade de um POS DIGITAL será possível ter acesso às principais funções de um estabelecimento como compra, venda, controle de estoque, relatórios, identificação dos clientes e funcionários, impressão por setor, e muito mais!" },
            { title: "Apliper Pagoo", logo: logo("logo-apliper"), description: "O Apliper Pagoo é um App para capturar o pagamento emitido pela automação desktop. Ao emitir uma NFC-e, o PDV gera uma requisição de pagamento e o App recebe esta requisição, processa o pagamento e retorna para o PDV (aprovada ou negada)." },
            { title: "APOS Skytef", logo: logo("logo-skytef"), description: "O APOS Skytef é um navegador Web para POS que realiza vendas por meio de diversas formas de pagamento. Com o APOS Skytef você pode customizar sua solução de pagamento (logomarca, cores, mensagens, etc.)." },
            { title: "Argo Sistemas", logo: logo("logo-argo"), description: "A solução Argo cobre todas as áreas vitais na operação de postos de gasolina. Os módulos do sistema foram pensados de forma inteligente, com a finalidade de integrar os dados, otimizando tempo e gerando informações essenciais para tomadas de decisão assertivas." },
            { title: "Arpag", logo: logo("logo-arpag"), description: "Você sofre com erros de digitação na hora da venda e acaba perdendo dinheiro? Precisa de mais agilidade nos pagamentos recebidos via Pix? A Arpa já tem uma solução para essas e outras situações do seu negócio - conheça o App Arpag, o integrador de PDV e SMART POS que facilita sua rotina." },
            { title: "B2 Sistemas", logo: logo("logo-b2"), description: "Integração com sistema Queen para recebimento integrado na maquininha." },
            { title: "Bar Fácil", logo: logo("logo-barfacil"), description: "O Bar Fácil é um App voltado para bares e eventos que atua como uma solução de ponto de venda (POS) Android, facilitando o gerenciamento de transações e operações de vendas." },
            { title: "BitBar", logo: logo("logo-bitbar"), description: "O Bit Bar é um sistema de gestão focado em Bares e Restaurantes." },
            { title: "Bitbyte", logo: logo("logo-bitbyte"), description: "A receita para o crescimento do seu negócio! Agilize o atendimento de seus clientes, reduza custos, evite desperdícios, melhore a lucratividade do seu negócio e automatize a apuração de informações estratégicas." },
            { title: "Brajan Sistemas", logo: logo("logo-brajan"), description: "App para atendimento de restaurante com controle de mesa e loja em geral." },
            { title: "Cash Driver", logo: logo("logo-idez"), description: "O Cash Driver é uma ferramenta que utiliza a tecnologia móvel (smartphone ou tablet) para acompanhar e otimizar o processo logístico de entrega. Seu ciclo tem início pela conferência dos produtos carregados (saída), prestação de contas e conferência de entrada." },
            { title: "CH Sistemas", logo: logo("logo-chsistemas"), description: "Simplifique as suas operações de vendas: Simples, prático e ágil, com uma interface amigável!" },
            { title: "Chef Mio", logo: logo("logo-chefmio"), description: "Atendimento presencial rápido e eficiente com App de garçom, cardápio digital para mesas através de QR Code, sistema de caixa rápido, mesas e comandas individuais. Automatize o atendimento de delivery e potencialize suas vendas." },
            { title: "CISS", logo: logo("logo-ciss"), description: "Com o App CISS é possível consultar informações sobre os produtos, emitir pedidos, gerar comandas, finalizar a venda e imprimir o documento fiscal de qualquer lugar da loja, ou até mesmo fora dela." },
            { title: "Closmaq", logo: logo("logo-losmaq"), description: "Software para gestão de mesa, balcão, entrega, ingressos, fichas e vendas no geral." },
            { title: "Código UP", logo: logo("logo-codigoup"), description: "O Código UP é uma ferramenta completa com vários módulos para gestão comercial." },
            { title: "Comanda Alterdata", logo: logo("logo-comanda-alterdata"), description: "O Comanda Alterdata é um aplicativo de lançamento de pedidos e vendas desenvolvido pela ALTERDATA Tecnologia em Informática LTDA. Ele é um aplicativo complementar e dependente do Alterdata SPICE, suíte completa de gestão voltada para restaurantes, bares, lanchonetes, cafeterias e estabelecimentos de food service." },
            { title: "COMPSIS", logo: logo("logo-compsis"), description: "App que faz o controle operacional e de cobranças em praças de pedágio." },
            { title: "Compu Forte Sistemas", logo: logo("logo-compuforte"), description: "App para venda de fichas em eventos, bares e restaurantes. *Lembrando que para rodar o App precisa do retaguarda da Compu Forte Sistemas." },
            { title: "Compumate Pay", logo: logo("logo-compumate"), description: "O sistema Compumate Pay é uma ferramenta que ajuda na realização das vendas com simplicidade e agilidade, tendo tudo na máquina de cartão. A POS Smart é uma maquininha que realizará a transação eletrônica com os cartões e no mesmo equipamento sairá a impressão do Cupom Fiscal (NFC-e)." },
            { title: "Compusoft", logo: logo("logo-compusoft"), description: "App integrado ao sistema de gestão de postos de combustíveis Posto Forte, o App permite que seja faturado os abastecimentos realizados nas bombas do posto, além de venda de produtos e controle da loja de conveniência." },
            { title: "Connect Posto - POS", logo: logo("logo-techposto"), description: "O Connect Posto - POS é um App de vendas de combustíveis do Connect Posto." },
            { title: "Consfor", logo: logo("logo-consfor"), description: "App para venda de tickets de estacionamento em eventos." },
            { title: "Datamais Garçom", logo: logo("logo-datamais"), description: "O App Datamais Garçom é destinado à automação da força de vendas em eventos, bares, restaurantes, cafeterias, pizzarias e similares. O App é capaz de imprimir tickets ou comandar pedidos para preparação, bem como efetuar a cobrança em cartões e Pix." },
            { title: "Datanis Sistemas", logo: logo("logo-datanis"), description: "Apps para gerenciamento de vendas externas, controle de estoque, Smart POS (Terminal TEF integrado ao sistema)." },
            { title: "DigiSat", logo: logo("logo-digisat"), description: "O App PDV Mobile 2.0 permite registrar vendas de produtos para consumidor final, com emissão de NFC-e, CF-e SAT ou Registro de Venda para empresas MEI." },
            { title: "DribionPay", logo: logo("logo-dribion"), description: "App totalmente integrado com nosso sistema para impulsionar vendas." },
            { title: "Droid PDV", logo: logo("logo-droidpdv"), description: "Droid PDV é uma solução de frente de caixa, para lojistas que precisam de uma ferramenta rápida e simples para registrar as suas vendas. O Droid PDV possui menus, botões e telas intuitivas para o fluxo de venda." },
            { title: "EAPOS", logo: logo("logo-easy"), description: "O EAPOS é um App para dispositivos móveis que veio para revolucionar o atendimento e o controle no segmento de food service." },
            { title: "easy", logo: logo("logo-easy"), description: "Facilite suas transações comerciais com o EASY, o App de integração de TEF que garante segurança, agilidade e eficiência nas suas operações de pagamento eletrônico." },
            { title: "ElPay", logo: logo("logo-elpay"), description: "Projetado para tornar o processo de receber pagamentos uma experiência sem complicações, o App ELPay oferece uma interface intuitiva e fácil de usar. Desenvolvido para máquinas de cartões Android, você pode aceitar pagamentos com cartões de crédito, débito e Pix de forma rápida e segura." },
            { title: "EPOC", logo: logo("logo-epoc"), description: "O EPOC é um PDV completo para restaurantes, com frente de caixa, gestão de pedidos e controle de vendas e estoque. Suporta operações por mesas, comanda, autoatendimento e PDV móvel." },
            { title: "EQuatro Pay", logo: logo("logo-e4quattropay"), description: "APP para gestão empresarial, com Consulta de produtos, faturamento, recebimento, dashboard e acompanhamento de vendas." },
            { title: "ErgonPDV", logo: logo("logo-ergon"), description: "App desenvolvido para auxiliar as equipes de vendas de um comércio ou distribuidora melhorar a sua eficiência e aumentar a produtividade, permite aos vendedores realizar orçamentos, pedidos e recebimento diretamente da SmartPOS." },
            { title: "eVogar", logo: logo("logo-vogar"), description: "Emitir notas fiscais, cupons e gerenciamento financeiro." },
            { title: "Eyemobile", logo: logo("logo-eyemobile"), description: "Sistema PDV direcionado para a jornada de venda em estabelecimentos, além do controle de estoque e de caixa. Todas as funcionalidades estão inclusas em um App compatível com as principais POS Digitais do mercado." },
            { title: "Fire Sistemas", logo: logo("logo-firesistemas"), description: "O App Fire Vendas proporciona agilidade e eficiência para Restaurantes. Os garçons podem abrir mesas, lançar pedidos, solicitar contas e emitir cupons fiscais diretamente de seus dispositivos móveis." },
            { title: "Gdoor Zucchetti", logo: logo("logo-gdoor"), description: "O PDV Móvel é um App que visa mobilidade e permite a emissão de NFC-e através do seu dispositivo mobile. Ele se conecta diretamente ao sistema retaguarda (necessário para funcionamento) e sincroniza as vendas emitidas instantaneamente." },
            { title: "GFood", logo: logo("logo-gfood"), description: "Sistema de gestão para bares e restaurantes que integra atendimento presencial, delivery, comandas, mesas, cardápio digital, autoatendimento e gestão operacional completa." },
            { title: "Idez", logo: logo("logo-idez"), description: "Somos uma plataforma de soluções financeiras B2B para você plugar ao seu negócio e gerar novas fontes de receita." },
            { title: "Infinite POS", logo: logo("logo-infinite"), description: "O Infinite POS é um PDV (Ponto de venda) móvel que traz uma nova forma de vendas para postos de combustíveis. Com o Infinite POS você será capaz de efetuar a venda de abastecimentos, produtos e emitir NFC-e diretamente da máquina de cartão." },
            { title: "Infosoft", logo: logo("logo-infosoft"), description: "O infosoft - ipay é um App que permite o recebimento de valores via cartão de crédito, débito ou Pix. Clientes que utilizam os produtos infosoft podem usufruir desta facilidade o que deixa o processo de vendas integrado e mais seguro." },
            { title: "JF System", logo: logo("logo-jfsystem"), description: "App de integração com softwares do Grupo JF System." },
            { title: "JR Restaurante", logo: logo("logo-jrsistemas"), description: "Aplicativo para uso do garçom: Permite fazer lançamentos de produtos em mesas, Efetuar pagamento e fechamento da mesa, Transferência de produtos entre mesas e etc." },
            { title: "Jump Serviços", logo: logo("logo-jump"), description: "Gerencie a distância, opere pelo App e tenha seu estacionamento ou lava-rápido na palma da mão! Atendemos perfeitamente tanto estacionamento, valet quanto lava-rápido ou estéticas automotivas." },
            { title: "Lion Pay", logo: logo("logo-lion"), description: "O Lion Pay é uma solução de automação comercial desenvolvida para atender às necessidades do comércio no estado de Mato Grosso. Com ele, você pode gerenciar vendas e operações de forma integrada." },
            { title: "Maistre", logo: logo("logo-maistre"), description: "App para recebimento de doações via cartão." },
            { title: "Master Key", logo: logo("logo-masterkeyfull"), description: "Master Key Smart TEF é uma solução que trabalha de forma Integrada ao Master Key, sistema de gestão e automação comercial. Foi desenvolvido para potencializar a gestão e o resultado das empresas de forma simples e segura." },
            { title: "Master Key Smart PDV", logo: logo("logo-masterkeyfull"), description: "A solução Smart PDV Master Key transforma seu terminal em um PDV móvel. O Smart PDV Master Key facilita a operação e reduz custos operacionais pois substitui o PDV convencional." },
            { title: "MC SISTEMAS", logo: logo("logo-mcsistemas"), description: "O MC Pag é um App que integra de forma rápida e fácil o PDV com seu SmartPOS. Uma solução que integra as vendas do PDV com o SmartPOS gerando maior segurança para o operador de caixa." },
            { title: "Menu Integrado", logo: logo("logo-menuintegrado"), description: "Plataforma completa para restaurantes e negócios de delivery, centralizando pedidos, oferecendo cardápio digital, gestão de motoboys, integrações com marketplaces e ferramentas de controle e automação." },
            { title: "Metanet Pay", logo: logo("logo-metanet"), description: "O Metanet Pay proporciona mobilidade dentro da sua empresa, facilitando o recebimento dos clientes com dinheiro, cartão e a prazo." },
            { title: "Mobi PDV e Mobi Comanda", logo: logo("logo-pdvmobi-comandamobi"), description: "Mobi PDV e Mobi Comanda, são pontos de venda móvel que facilita sua operação e reduz custos. Dispensa todos os equipamentos do seu ponto de venda, emite Fichas, Pedidos ou NFC-e." },
            { title: "Mobility", logo: logo("logo-mobility"), description: "A solução da Mobility é para a frente de caixa. Ideal para lojistas que precisam de uma ferramenta rápida e simples para registrar as suas vendas." },
            { title: "MobPay", logo: logo("logo-raffinato"), description: "O App MobPay permite efetuar o pagamento de contas geradas no Raffinato, tanto pedidos realizados no App Raffinato Mobile (Garçom), como no PDV desktop. Este App funciona de forma integrada ao Raffinato Gestor." },
            { title: "mPm+", logo: logo("logo-mpm"), description: "O App mPm+ é uma ferramenta de vendas móveis." },
            { title: "MR PDV", logo: logo("logo-rpinfo"), description: "O App MR PDV, da RP Info, é um sistema robusto e confiável, para registro de vendas no seu PDV. Com ele, é possível gerenciar de forma centralizada todos os caixas e ECFs de lojas individuais ou redes." },
            { title: "MToll", logo: logo("logo-mtoll"), description: "O MTOLL é um aplicativo de arrecadação e operação móvel para praças de pedágio, desenvolvido pela COMPSIS. A solução permite que operadores realizem cobrança de pedágio de forma móvel, diretamente em Smart POS." },
            { title: "NCR", logo: logo("logo-ncr"), description: "Solução NCR para terminais de pagamento." },
            { title: "OmniPDV", logo: logo("logo-omni"), description: "Com a plataforma Nexaas.Omni você terá gestão e controle do seu negócio com facilidade e mobilidade. App para sistema de PDV e caixa de loja 100% móvel, funciona de qualquer lugar." },
            { title: "ONPDV", logo: logo("logo-onpdv"), description: "O ONPDV é um sistema de gestão para varejo e food service. Controle estoques, vendas e finanças em tempo real, otimize pedidos e personalize promoções." },
            { title: "Origam", logo: logo("logo-origam"), description: "Controle de mesas e comandas para clientes que utilizam o Godino." },
            { title: "PagZilla", logo: logo("logo-pagzilla"), description: "Com o Pagzilla você passa o cartão e imediatamente emite sua NFC-e. Integre o pagamento com o cartão de débito ou crédito com seu dispositivo junto ao SAT." },
            { title: "PDV Legal", logo: logo("logo-pdvlegal"), description: "O PDV Legal é o sistema de vendas ideal para você que busca agilidade e facilidade no seu processo de vendas. Com telas de fácil navegação você pode emitir documentos fiscais, controlar seu estoque e gerenciar todas as suas vendas utilizando apenas a sua maquininha." },
            { title: "PDV POS", logo: logo("logo-pdvpos"), description: "Faça vendas, emita notas fiscais e controle toda a sua empresa, do estoque ao financeiro, tudo online e muito fácil de usar." },
            { title: "PDV Team17", logo: logo("logo-team17"), description: "O App PDV Team17 possui um sistema completo com as seguintes funcionalidades: ERP, PDV Frente de caixa, emissor de tickets, cashless, caixa móvel, emissor NFCe." },
            { title: "Pixei Pagamentos", logo: logo("logo-pixei"), description: "Realize vendas e pedidos, finalize e reserve comandas, integrado ao NooChef - Alimentação, desenvolvido pela Nootech Sistemas." },
            { title: "PlinPag", logo: logo("logo-plimpag"), description: "Consulta, impressão e pagamento de faturas de água de concessionárias parceiras e tributos municipais." },
            { title: "POS Controle", logo: logo("logo-poscontrole"), description: "O POS Controle é um PDV móvel que facilita a sua operação e reduz custos. Dispensa todos os equipamentos do seu ponto de venda, emite fichas, pedidos ou NFC-e." },
            { title: "Posto Gestor", logo: logo("logo-postogestor"), description: "O Posto Gestor é um sistema de gestão completo e especializado para o varejo de combustíveis, conveniências, troca de óleo e serviços." },
            { title: "PrátikaPDV", logo: logo("logo-pratika"), description: "O PrátikaPDV é um App de gerenciamento de vendas que funciona diretamente no smartphone, SmartPOS ou computador (PC), permitindo que vários ramos possam utilizar a aplicação." },
            { title: "Prioriza", logo: logo("logo-prioriza"), description: "App de restaurantes / evento, para auxiliar na venda de itens e impressão de ticket, contando com um meio de pagamento direto." },
            { title: "PSinf Pay", logo: logo("logo-infosolucoes"), description: "O PSinf Pay é uma solução que visa a integração dos meios de pagamento TEF com o sistema ERP da PSInf, proporcionando a automação dos processos de pagamento." },
            { title: "Puma Sistemas", logo: logo("logo-puma"), description: "O Módulo PDV é recomendado para lojas e diversos tipos de comércio que costumam lidar com um grande fluxo diário de clientes e precisam realizar uma venda rápida e ágil." },
            { title: "Queóps Bares & Restaurantes", logo: logo("logo-queops"), description: "Bares & Restaurantes tenha mais controle, mais automação, mais pedidos, mais eficiência e mais integração. O sistema Queóps é desenvolvido para aprimorar a gestão do seu negócio com soluções personalizadas." },
            { title: "RANFCe", logo: logo("logo-RANFCe"), description: "NFC-e Nota de Consumidor em Tablet, Smartphone, Terminal G800, Cielo LIO e REDE com GPOS700 e L400. Pré-Atendimento/Orçamento para Tablet e Smartphone." },
            { title: "Rei das Fichas", logo: logo("logo-reidasfichas"), description: "Sistema para emissão de fichas/tickets e controle de consumo em eventos, bares e operações que usam vendas rápidas." },
            { title: "Relt Informática", logo: logo("logo-relt"), description: "App de força de vendas e emissor de notas fiscais do ERP SiG." },
            { title: "RMS Mobile", logo: logo("logo-resultmais"), description: "Aplicativo desenvolvido para terminais POS, voltado ao processamento de transações de pagamento via cartão (crédito/débito) e Pix. Com interface simples e intuitiva, permite a realização rápida e segura de vendas." },
            { title: "Santa Ficha", logo: logo("logo-santaficha"), description: "Sistema de gestão para emissão de fichas e cartão de consumo para eventos." },
            { title: "Serbet", logo: logo("logo-serbet"), description: "Sistema de fiscalização e vendas de estacionamento rotativo (zona azul) das cidades operadas pelo Estacionamento Digital." },
            { title: "SEUPOS Food", logo: logo("logo-seupos"), description: "Aplicativo de ponto de venda (POS) para bares, restaurantes, pizzarias e cafés, permitindo gestão de pedidos, mesas, cardápio digital, vendas e controle financeiro em tempo real." },
            { title: "SG Pay", logo: logo("logo-sgbr"), description: "O SG Pay é uma solução de pagamentos que possibilita a realização do processo de pagamento de forma integrada com sistema SG Master." },
            { title: "Sismec", logo: logo("logo-sismec"), description: "App para automação de cobranças realizadas através do Sismec Mobile. Tenha total controle das receitas e despesas de sua empresa." },
            { title: "SISMOV2B", logo: logo("logo-opcaovirtual"), description: "Sistema SISMOV2B para automação comercial." },
            { title: "Sistema Pallas", logo: logo("logo-resultmais"), description: "Controle as vendas, estoque e as finanças." },
            { title: "Smart POS", logo: logo("logo-poscontrole"), description: "O Smart POS da NetPOS é um App para varejo geral que permite uma gestão integrada dos PDVs com controle de estoque e vendas." },
            { title: "Softcom Smart", logo: logo("logo-softcom"), description: "O Softcom Smart é a solução ideal para empresas que buscam modernizar e otimizar suas operações. Com o Softcom Smart, você pode vender mais, aceitar cartões de crédito e emitir cupons fiscais (NFC-e) com facilidade." },
            { title: "Softplus", logo: logo("logo-softplus"), description: "O App Softplus é um Ponto de Venda para Postos de combustível. Atende a venda (abastecimentos) por meio de uma solução completa com pagamento em dinheiro, cartão, Pix e venda a prazo." },
            { title: "SOS Soluções", logo: logo("logo-sos"), description: "O NextMobile é o App complementar aos ERP Next360 que contempla no App as funções integradas com TEF." },
            { title: "SousaVenda", logo: logo("logo-sousavendas"), description: "O App SousaVenda é desenvolvido para as diferentes empresas do ramo do comércio com faturamento até R$ 50 mil reais por mês." },
            { title: "SUIT EXPRESS POS", logo: logo("logo-suitablev3"), description: "Aplicativo para motoboys, permitindo controle completo de entregas, rota, comunicação com cliente e atualização de status em tempo real." },
            { title: "Suit POS", logo: logo("logo-suitpos"), description: "O SuitPOS é de uso exclusivo de clientes Suitable. Sua função é servir como integração de pagamentos de pedidos de forma automatizada, gerando comprovante e Nota Fiscal." },
            { title: "SUIT WAITER POS", logo: logo("logo-suitablev4"), description: "Aplicativo de garçom / comanda eletrônica, permitindo lançar pedidos na mesa, enviar à cozinha, gerir comandas e realizar pagamento direto na mesa." },
            { title: "Super PDV", logo: logo("logo-superpdv"), description: "Aplicativo PDV Mobile da BM Informática para realização de pedidos, comandas e vendas." },
            { title: "Suporte PDV Mobile", logo: logo("logo-suporte"), description: "O Suporte PDV Mobile é um App de Ponto de Venda móvel para postos de combustível." },
            { title: "Tacto Sistemas", logo: logo("logo-tacto"), description: "Módulo de venda mais completo do mercado, utilizado para atender bares, restaurantes, sorveterias, lanchonetes e até boates. Existem várias maneiras de trabalhar a venda neste módulo." },
            { title: "Tech Posto", logo: logo("logo-techposto"), description: "Tech Posto - PDV em suas mãos." },
            { title: "THR Softwares", logo: logo("logo-thr"), description: "App voltado para vendas de produtos e ingressos em parques aquáticos." },
            { title: "Ticket PDV", logo: logo("logo-ticketpdv"), description: "Sistema simples e rápido de PDV para eventos, festas e bares, permitindo emissão de tickets, controle básico de estoque, fechamento de caixa e vendas à vista." },
            { title: "Trade System", logo: logo("logo-tradesystem"), description: "O App Trade System para gestão comercial integrada." },
            { title: "UNIO", logo: logo("logo-unio"), description: "O UNIO PDV Mobile é um sistema que contempla Pré Venda, Controle de Fabricação, Baixa rápida de cupom, alteração de preços de bomba, carta frete, vale motorista." },
            { title: "Uniplus", logo: logo("logo-uniplus"), description: "O sistema Uniplus possui funcionalidades e integrações específicas para o segmento Food Service, feitas especialmente para agilizar o dia a dia do seu cliente." },
            { title: "Unypax", logo: logo("logo-unypax"), description: "App de recebimento integrado com o ERP Unypax." },
            { title: "Vedas Sistemas", logo: logo("logo-vedas"), description: "App com integração com nosso App de garçom, pagamentos avulsos, recebimentos na mesa e pagamento PDV integrado." },
            { title: "Veloce Smart", logo: logo("logo-velocetech"), description: "Automação comercial integrada à máquina de pagamentos, ideal para todos os segmentos. Desenvolvida para otimizar suas vendas e oferecer uma gestão completa do negócio." },
            { title: "VucaPOS", logo: logo("logo-vuca"), description: "VucaPOS é uma solução de ponto de venda (PDV) integrada ao ERP Vuca Solution, projetada para simplificar e agilizar as operações de frente de caixa." },
            { title: "WebPosto", logo: logo("logo-webposto"), description: "O webPosto Pay é um App focado no setor de postos de combustível. Integrado às bombas de abastecimento, permite ao frentista realizar a venda, receber nas diversas formas de pagamento e emitir o cupom de venda diretamente no POS." },
            { title: "WebyAPP", logo: logo("logo-webyapp"), description: "O WebyAPP é a solução para pontos de venda com emissão de NFC-e, faz emissão e controle de acesso de ingressos com QR Code e emissão de tickets para eventos." },
            { title: "Wesa SmartPDV", logo: logo("logo-wesa"), description: "O App SmartPDV possibilita muito mais do que passar cartão no seu ponto de venda móvel, ele é um sistema de vendas completo para postos de combustíveis." },
            { title: "Windel POS", logo: logo("logo-windel"), description: "O Windel POS é um App integrado ao sistema Windel que facilita o processamento de pagamentos de vendas em estabelecimentos comerciais." },
            { title: "Xmenu", logo: logo("logo-menuintegrado"), description: "Aplicativo completo para gestão de PDV para restaurantes, com controle de mesa, balcão e delivery." },
            { title: "Yolo PDV", logo: logo("logo-yolo"), description: "A Yolo Pass é a solução completa de cashless para organizadores de eventos, oferecendo uma plataforma que integra controle de acesso, venda e validação de ingressos digitais, recarga de saldo e consumo via pulseiras ou cartões RFID." },
            { title: "Youzoom", logo: logo("logo-youzoom"), description: "App de PDV para venda de ingressos e produtos com emissão de voucher com QR Code!" },
            { title: "Zenitech", logo: logo("logo-zenitech"), description: "Aplicação da Zenitech para operação em terminais AXIUM DX8000, usados como SmartPOS Android para automação comercial e pagamentos." },
            { title: "zerofila", logo: logo("logo-new-choice"), description: "Controle total e pagamentos simplificados: A POS Multiloja com Split de Pagamento que facilita suas vendas e garante a divisão automática de receitas entre as lojas." },
            { title: "Zetta Pay", logo: logo("logo-zetta"), description: "Ajudar empresas com alto volume de cobranças mensais a automatizar e agilizar seus recebimentos através de um sistema de gestão de cobranças." },
            { title: "ZPOS", logo: logo("logo-zpos"), description: "O App ZPOS faz vínculo entre o serviço de transação ofertado pelo parceiro, recebendo as informações dos sistemas Zucchetti para que seja efetuado a transação no SmartPOS do parceiro." },
        ],
    },
    { label: "Atacado", items: [] },
    { label: "Auto Elétricas, Auto Peças e Mecânicas", items: [] },
    { label: "Bar", items: [] },
    { label: "Comércio", items: [] },
    { label: "Delivery", items: [] },
    { label: "Direito", items: [] },
    { label: "Distribuidores de Produtos", items: [] },
    { label: "Estacionamentos", items: [] },
    { label: "Eventos, Feiras e Shows", items: [] },
    { label: "Ferragem", items: [] },
    { label: "Fidelidade e Convênios", items: [] },
    { label: "Food Service e Food Truck", items: [] },
    { label: "Gestão de Pedidos", items: [] },
    { label: "Gestão Empresarial", items: [] },
    { label: "Hotéis", items: [] },
    { label: "Indústrias", items: [] },
    { label: "Ingressos", items: [] },
    { label: "Lanchonetes e Restaurantes", items: [] },
    { label: "Lojas de Confecção, Calçados e Vestuário", items: [] },
    { label: "Lojas de Conveniência", items: [] },
    { label: "Materiais de Construção", items: [] },
    { label: "Padarias", items: [] },
    { label: "Pedágio", items: [] },
    { label: "Postos de Combustível", items: [] },
    { label: "Religioso", items: [] },
    { label: "Salão de Beleza", items: [] },
    { label: "Saúde", items: [] },
    { label: "Serviços", items: [] },
    { label: "Sorveterias", items: [] },
    { label: "Supermercados", items: [] },
    { label: "Transporte", items: [] },
    { label: "Varejo em Geral", items: [] },
    { label: "Venda de Seguros", items: [] },
];

export default appsData;
